language: scala

scala:
  - 2.12.6

script:
  - sbt coverage test 'it:testOnly -- timefactor 5' coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - openssl aes-256-cbc -K $encrypted_32189a0b8162_key -iv $encrypted_32189a0b8162_iv
    -in project/sec.tgz.enc -out project/sec.tgz -d
  - (cd project/ && tar zxf sec.tgz)
  - chmod 600 project/travis-deploy-key
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key

deploy:
  skip_cleanup: true
  provider: script
  script: sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS +publishSigned paradox ghpagesPushSite
  on:
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
